# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\User\Desktop\МАКСИМ!\Магистратура\ВКР\resource allocation\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(842, 532)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_options = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_options.setGeometry(QtCore.QRect(500, 50, 301, 31))
        self.pushButton_options.setObjectName("pushButton_options")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(810, 30, 31, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(9, 9, 481, 391))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_graph = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_graph.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_graph.setObjectName("verticalLayout_graph")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 410, 481, 31))
        self.pushButton.setObjectName("pushButton")
        self.spinBox_count_of_tasks = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_count_of_tasks.setGeometry(QtCore.QRect(150, 450, 91, 31))
        self.spinBox_count_of_tasks.setObjectName("spinBox_count_of_tasks")
        self.label_name_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_name_1.setGeometry(QtCore.QRect(10, 450, 81, 31))
        self.label_name_1.setObjectName("label_name_1")
        self.label_name_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_name_2.setGeometry(QtCore.QRect(260, 450, 131, 31))
        self.label_name_2.setObjectName("label_name_2")
        self.doubleSpinBox_connection_probability = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_connection_probability.setGeometry(QtCore.QRect(400, 450, 91, 31))
        self.doubleSpinBox_connection_probability.setMaximum(1.0)
        self.doubleSpinBox_connection_probability.setObjectName("doubleSpinBox_connection_probability")
        self.pushButton_poke = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_poke.setGeometry(QtCore.QRect(500, 10, 301, 31))
        self.pushButton_poke.setObjectName("pushButton_poke")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(810, 0, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.label_1.setFont(font)
        self.label_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_1.setObjectName("label_1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 842, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "resource allocation "))
        self.pushButton_options.setText(_translate("MainWindow", "Searching for options "))
        self.label_2.setText(_translate("MainWindow", "•"))
        self.pushButton.setText(_translate("MainWindow", "Generate Graph"))
        self.label_name_1.setText(_translate("MainWindow", "count of nodes"))
        self.label_name_2.setText(_translate("MainWindow", "connection probability"))
        self.pushButton_poke.setText(_translate("MainWindow", "Scientific poke method"))
        self.label_1.setText(_translate("MainWindow", "•"))
